# Generated by Django 5.0.1 on 2024-02-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactenquriry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactenquiry',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='contactenquiry',
            name='websiteLink',
        ),
        migrations.AddField(
            model_name='contactenquiry',
            name='subject',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactenquiry',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contactenquiry',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
