# Generated by Django 5.0.1 on 2024-03-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactenquriry', '0002_remove_contactenquiry_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='singlepost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=50)),
                ('message', models.TextField()),
            ],
        ),
    ]
